name: focust
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.4.0
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/splash_icon.png
    - assets/images/usto_note.png
    - assets/images/usto_1.png
    - assets/images/usto_2.png
    - assets/images/usto_widget.png
    - assets/images/timer_usto1.png
    - assets/images/tebrik_usto.png
    - assets/images/pomodoro_timer.png
    - assets/images/note_image.png
    - assets/images/noel_usto.png

